import { NgModule } from '@angular/core';

import {
  MatButtonModule,
  MatToolbarModule,
  MatCheckboxModule,
  MatMenuModule,
  MatIconModule,
  MatCardModule,
  MatInputModule,
  MatSidenavModule,
  MatDividerModule,
  MatListModule,
  MatFormFieldModule,
  MatSelectModule,
  MatTabsModule,
  MatGridListModule,
  MatButtonToggleModule,
  MatSlideToggleModule,
  MatRadioModule,
  MatTableModule,
  MatPaginatorModule,
  MatProgressSpinnerModule,
  MatSnackBarModule,
  MatButtonToggleGroup,
  MatButtonToggle,
  MatSlideToggle,
  MatButton,
  MatRadioGroup,
  MatRadioButton,
  MatTab,
  MatGridList,
  MatGridTile,
  MatPaginator,
  MatSpinner,
  MatDialogModule,
  MatTooltipModule,

} from '@angular/material';

@NgModule({
  declarations: [],
  imports: [
    MatButtonModule,
    MatToolbarModule,
    MatCheckboxModule,
    MatMenuModule,
    MatIconModule,
    MatCardModule,
    MatInputModule,
    MatSidenavModule,
    MatDividerModule,
    MatListModule,
    MatFormFieldModule,
    MatSelectModule,
    MatTabsModule,
    MatGridListModule,
    MatButtonToggleModule,
    MatSlideToggleModule,
    MatRadioModule,
    MatGridListModule,
    MatTableModule,
    MatPaginatorModule,
    MatProgressSpinnerModule,
    MatSnackBarModule,
    MatDialogModule,
  ],
  exports: [
    MatButtonModule,
    MatToolbarModule,
    MatCheckboxModule,
    MatMenuModule,
    MatIconModule,
    MatCardModule,
    MatInputModule,
    MatSidenavModule,
    MatDividerModule,
    MatListModule,
    MatFormFieldModule,
    MatSelectModule,
    MatTabsModule,
    MatGridListModule,
    MatTableModule,
    MatSnackBarModule,
    MatButtonToggleGroup,
    MatButtonToggle,
    MatSlideToggle,
    MatButton,
    MatRadioGroup,
    MatRadioButton,
    MatTab,
    MatGridList,
    MatGridTile,
    MatPaginator,
    MatSpinner,
    MatDialogModule
  ]
})
export class MaterialModule { }
