// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-2",
    "aws_cognito_identity_pool_id": "us-east-2:95086ad3-333a-4748-8d82-584528fdc9b2",
    "aws_cognito_region": "us-east-2",
    "aws_user_pools_id": "us-east-2_IjOMMIeaC",
    "aws_user_pools_web_client_id": "3sv06ve0306t8g8obodvjksaes"
};


export default awsmobile;
